[package]
name = "pb-test"
version = "0.1.0"
authors = ["Rajat Goel <rajat@dropbox.com>", "Nipunn Koorapati <nipunn@dropbox.com>", "Parker Timmerman <parkertimmerman@dropbox.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5.6"
pb = { git = "ssh://git@github.com/dropbox/pb-rs.git" }
pretty_assertions = "0.6.1"
proto_pbtest = { path = "gen/rust/proto/proto_pbtest" }
proto_google = { path = "gen/rust/proto/proto_google" }

[build-dependencies]
pb-gen = { path = "../pb-gen" }
