[package]
name = "pb-jelly"
description = "A protobuf runtime for the Rust language developed at Dropbox"
version = "0.0.1"
authors = ["Rajat Goel <rajat@dropbox.com>", "Nipunn Koorapati <nipunn@dropbox.com>", "Parker Timmerman <parkertimmerman@dropbox.com>"]
edition = "2018"
license-file = "LICENSE"
homepage = "https://github.com/dropbox/pb-rs"
repository = "https://github.com/dropbox/pb-rs"
keywords = ["google", "protobuf", "proto", "dropbox"]
categories = ["encoding", "parsing", "web-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.4"
bytes = "0.5.6"
serde = { version = "1.0.114", features = ["derive"] }
